// in table view: https://docs.google.com/spreadsheets/d/1D6l0KnaemCNLSWCuSUvlljfsmhA45UiMhDwQByot9xU/edit?usp=sharing
const STD = {
 'list':    { 'whitespace':   { '*': {toState: 'list'}}, 
              '(':            { '*': {toState: 'list', SAction: ['push', 'L'],  action: ['addList']}},
              ')':            { '#': {                                          action: ['error', 'Invalid ")"']},
                                'L': {toState: 'list', SAction: ['pop', 'L'],}},
              'char-or-digit':{ '#': {                                          action: ['error', 'Atom outside any list']},
                                'L': {toState: 'atom',                          action: ['appendCharToBuffer']}},
              "'":            { '*': {toState: 'quote'}},
              '"':            { '*': {toState: 'string'}},
              ';':            { '*': {toState: 'comment'}},
              'EOL':          { '*': {toState: 'list',                          action: ['newLine']}},
              'EOF':          { '#': {toState: 'end'},
                                'L': {                                          action: ['error', 'Open list at the end of file']}},
            }, 
 'atom':    { 'whitespace':   { '*': {toState: 'list'}}, 
              '(':            { '*': {toState: 'list', SAction: ['push', 'L'],  action: ['addList']}},
              ')':            { '*': {toState: 'list', SAction: ['pop', 'L'],}},
              'char-or-digit':{ '*': {toState: 'atom',                          action: ['appendCharToBuffer']}},
              "'":            { '*': {toState: 'quote'}},
              '"':            { '*': {toState: 'string'}},
              ';':            { '*': {toState: 'comment'}},
              'EOL':          { '*': {toState: 'list',                          action: ['newLine']}},
              'EOF':          { '*': {                                          action: ['error', 'Unexpected EOF in atom']}},
            },
 'string':  { 'whitespace':   { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              '(':            { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              ')':            { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              'char-or-digit':{ '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              "'":            { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              '"':            { '*': {toState: 'list'}},
              ';':            { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              'EOL':          { '*': {toState: 'string',                        action: ['appendCharToBuffer']}}, 
              'EOF':          { '*': {                                          action: ['error', 'Unexpected EOF in string']}},
            },
 'comment': { 'whitespace':   { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              '(':            { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              ')':            { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              'char-or-digit':{ '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              "'":            { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}},
              '"':            { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              ';':            { '*': {toState: 'comment',                       action: ['appendCharToBuffer']}}, 
              'EOL':          { '*': {toState: 'list',                          action: ['newLine']}},
              'EOF':          { '#': {toState: 'end'},
                                'L': {                                          action: ['error', 'Open list at the end of file']}},
            },
 'quote':   { 'whitespace':   { '*': {                                          action: ['error', 'Unexpected space after quotation mark']}},
              '(':            { '*': {toState: 'list',SAction: ['push', 'L'],   action: ['addQuotedList']}}, 
              ')':            { '*': {                                          action: ['error', 'Unexpected ) after quotation mark']}},
              'char-or-digit':{ '*': {                                          action: ['error', 'Unexpected symbol after quotation mark']}},
              "'":            { '*': {                                          action: ['error', 'Unexpected \' after quotation mark']}},
              '"':            { '*': {                                          action: ['error', 'Unexpected " after quotation mark']}},
              ';':            { '*': {                                          action: ['error', 'Unexpected ; after quotation mark']}},
              'EOL':          { '*': {                                          action: ['error', 'Unexpected EOL after quotation mark']}},
              'EOF':          { '*': {                                          action: ['error', 'Unexpected EOF after quotation mark']}},
            },
};

module.exports = { STD };